baseURL       = "https://charline-royer-nws.netlify.app/"
languageCode  = "fr-FR"
title         = "Roxo | NWS portfolio starter theme"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "HOME"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "À PROPOS"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "PORTFOLIO"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "BLOG"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "CONTACT"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = ""
    heading               = "Faisons de votre projet une réalité !"
    tagline               = ""
    primary_button        = "Tous mes projets"
    primary_button_url    = "portfolio"
    secondary_button      = "Contactez-moi"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "Mes récents projets"
    subtitle  = ""

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "TRAVAILLONS ENSEMBLE"
    primary_button      = "Contact"
    primary_button_url  = "contact"
    secondary_button    = "Tous mes projets"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Information contact"
      address = ""
      phone   = "06.27.21.29.80"
      email   = "croyer@normandiewebschool.fr"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Plan du site"
        [[params.footer.sitemap.link]]
          name = "À propos"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Projets"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Réseaux sociaux"
        [[params.footer.social.link]]
          name = "GitHub"
          url  = "https://github.com/CharlineRoyer"
        [[params.footer.social.link]]
          name = "Linkedin"
          url  = "https://www.linkedin.com/in/charline-royer/"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
        [[params.footer.social.link]]
          name = ""
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "Ce que je fais :"
        description = "Développement web<br>Design"